[versions]
kotlin = "2.3.0"
intellij-platform = "2.10.5"
intellij-version = "2025.1"
java-compatibility = "21"
since-build = "251"
junit-jupiter = "6.0.1"
junit-platform-launcher = "6.0.1"
junit = "4.13.2"
ktlint-gradle = "14.0.1"
detekt = "1.23.8"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
